from django.urls import path
from .views import (
    register_candidate,
    register_recruiter,
    login,
    create_organization_view,
    list_organizations_view,
    delete_organization_view,
    create_recruiter_view,
    list_active_recruiters_view,
    deactivate_recruiter_view,
    organization_settings_view,
    organization_invites_view,
    resend_organization_invite_view,
    revoke_organization_invite_view,
    organization_invite_lookup_view,
    accept_organization_invite_view,
    public_organization_profile_view,
    platform_metrics_view,
    system_health_view,
    top_organizations_view,
    recent_activity_view,
    organization_status_view,
)

urlpatterns = [
    path('register/', register_candidate),
    path('register/recruiter/', register_recruiter),
    path('login/', login),
    path('organizations/', list_organizations_view),
    path('organizations/create/', create_organization_view),
    path('organizations/<int:organization_id>/delete/', delete_organization_view),
    path('organizations/<int:organization_id>/status/', organization_status_view),
    path('recruiters/', list_active_recruiters_view),
    path('recruiter/create/', create_recruiter_view),
    path('recruiter/deactivate/<int:user_id>/', deactivate_recruiter_view),
    path('organization/settings/', organization_settings_view),
    path('organization/invites/', organization_invites_view),
    path('organization/invites/<int:invite_id>/resend/', resend_organization_invite_view),
    path('organization/invites/<int:invite_id>/revoke/', revoke_organization_invite_view),
    path('organization/invites/lookup/<str:token>/', organization_invite_lookup_view),
    path('organization/invites/accept/', accept_organization_invite_view),
    path('organization/public/<slug:organization_slug>/', public_organization_profile_view),
    # SuperAdmin endpoints
    path('admin/platform-metrics/', platform_metrics_view),
    path('admin/system-health/', system_health_view),
    path('admin/top-organizations/', top_organizations_view),
    path('admin/recent-activity/', recent_activity_view),
]
