# Generated by Django 5.2.12 on 2026-03-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0007_alter_jobapplication_options_and_more'),
        ('resumes', '0005_alter_education_options_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('normalized_score', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('model_version', models.CharField(max_length=100, null=True)),
                ('processing_time_ms', models.IntegerField(null=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='jobs.jobdescription')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='resumes.resume')),
            ],
            options={
                'db_table': 'ai_processing_logs',
            },
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='jobs.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='resumes.resume')),
            ],
            options={
                'db_table': 'match_scores',
            },
        ),
    ]
