# Generated by Django 5.2.12 on 2026-03-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobapplication_options_and_more'),
        ('matching', '0001_initial'),
        ('resumes', '0005_alter_education_options_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiprocessinglog',
            options={'ordering': ['-processed_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='matchscore',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterField(
            model_name='matchscore',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='aiprocessinglog',
            index=models.Index(fields=['resume'], name='ai_log_resume_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessinglog',
            index=models.Index(fields=['job'], name='ai_log_job_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessinglog',
            index=models.Index(fields=['processed_at'], name='ai_log_processed_at_idx'),
        ),
        migrations.AddIndex(
            model_name='matchscore',
            index=models.Index(fields=['resume'], name='match_resume_idx'),
        ),
        migrations.AddIndex(
            model_name='matchscore',
            index=models.Index(fields=['job'], name='match_job_idx'),
        ),
        migrations.AddIndex(
            model_name='matchscore',
            index=models.Index(fields=['-score'], name='match_score_desc_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiprocessinglog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('raw_score__gte', 0), ('raw_score__lte', 1)), ('raw_score__isnull', True), _connector='OR'), name='ai_log_raw_score_between_zero_and_one'),
        ),
        migrations.AddConstraint(
            model_name='aiprocessinglog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('normalized_score__gte', 0), ('normalized_score__lte', 1)), ('normalized_score__isnull', True), _connector='OR'), name='ai_log_normalized_score_between_zero_and_one'),
        ),
        migrations.AddConstraint(
            model_name='aiprocessinglog',
            constraint=models.CheckConstraint(condition=models.Q(('processing_time_ms__gte', 0), ('processing_time_ms__isnull', True), _connector='OR'), name='ai_log_processing_time_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='matchscore',
            constraint=models.UniqueConstraint(fields=('resume', 'job'), name='uniq_resume_job_match_score'),
        ),
        migrations.AddConstraint(
            model_name='matchscore',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 1)), name='match_score_between_zero_and_one'),
        ),
    ]
