# Generated by Django 5.2.12 on 2026-03-22 19:28

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='resume',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, null=True),
        ),
    ]
