# Generated by Django 5.2.12 on 2026-03-27 18:46

from django.db import migrations, models


def backfill_resume_storage_and_primary(apps, schema_editor):
    Resume = apps.get_model("resumes", "Resume")

    for resume in Resume.objects.all():
        updates = []
        if resume.cloud_url:
            if str(resume.cloud_url).startswith("http"):
                if resume.storage_backend != "supabase":
                    resume.storage_backend = "supabase"
                    updates.append("storage_backend")
                if not resume.storage_path:
                    resume.storage_path = resume.cloud_url
                    updates.append("storage_path")
            else:
                if resume.storage_backend != "local":
                    resume.storage_backend = "local"
                    updates.append("storage_backend")
                if not resume.storage_path:
                    resume.storage_path = resume.cloud_url
                    updates.append("storage_path")
        if updates:
            resume.save(update_fields=updates)

    candidate_ids = Resume.objects.values_list("candidate_id", flat=True).distinct()
    for candidate_id in candidate_ids:
        candidate_resumes = list(
            Resume.objects.filter(candidate_id=candidate_id, is_active=True).order_by("-uploaded_at", "-id")
        )
        if not candidate_resumes:
            continue
        primary_id = candidate_resumes[0].id
        Resume.objects.filter(candidate_id=candidate_id).exclude(id=primary_id).update(is_primary=False)
        Resume.objects.filter(id=primary_id).update(is_primary=True)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('candidates', '0003_alter_candidate_options_candidate_user_and_more'),
        ('resumes', '0004_alter_experience_id_alter_project_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_year', '-start_year', '-id']},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['skill_name', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='resume',
            name='resumes_candida_87bf8f_idx',
        ),
        migrations.RenameIndex(
            model_name='resume',
            new_name='resume_parsing_status_idx',
            old_name='resumes_parsing_306841_idx',
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='resume_skill_name_idx',
            old_name='skills_skill_n_b9a819_idx',
        ),
        migrations.AddField(
            model_name='resume',
            name='checksum_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='storage_backend',
            field=models.CharField(choices=[('supabase', 'Supabase'), ('local', 'Local')], db_index=True, default='supabase', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='storage_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='cloud_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='parsing_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, max_length=50, null=True),
        ),
        migrations.RunPython(backfill_resume_storage_and_primary, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['candidate', 'is_active'], name='resume_candidate_active_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['candidate', 'uploaded_at'], name='resume_candidate_uploaded_idx'),
        ),
        migrations.AddConstraint(
            model_name='education',
            constraint=models.CheckConstraint(condition=models.Q(('end_year__gte', models.F('start_year')), ('end_year__isnull', True), ('start_year__isnull', True), _connector='OR'), name='education_year_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), ('start_date__isnull', True), _connector='OR'), name='experience_date_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.CheckConstraint(condition=models.Q(('duration_months__gte', 0), ('duration_months__isnull', True), _connector='OR'), name='experience_duration_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), ('start_date__isnull', True), _connector='OR'), name='project_date_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__gte', 0), ('file_size__isnull', True), _connector='OR'), name='resume_file_size_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('candidate',), name='uniq_active_primary_resume_per_candidate'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('resume', 'skill_name'), name='uniq_resume_skill_name'),
        ),
    ]
