# Generated by Django 5.2.12 on 2026-03-27 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidate_options_candidate_user_and_more'),
        ('jobs', '0006_backfill_posted_by_for_existing_jobs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='jobdescription',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='jobskill',
            options={'ordering': ['skill', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('interviewed', 'Interviewed'), ('rejected', 'Rejected'), ('hired', 'Hired')], db_index=True, default='applied', max_length=20),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='app_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['candidate', 'status'], name='app_candidate_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applied_at'], name='app_applied_at_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['posted_by', 'is_active'], name='job_owner_active_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['is_active', 'created_at'], name='job_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['location'], name='job_location_idx'),
        ),
        migrations.AddIndex(
            model_name='jobskill',
            index=models.Index(fields=['skill'], name='job_skill_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='uniq_candidate_job_application'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.CheckConstraint(condition=models.Q(('expected_salary__gte', 0), ('expected_salary__isnull', True), _connector='OR'), name='application_expected_salary_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='jobdescription',
            constraint=models.CheckConstraint(condition=models.Q(('salary_min__gte', 0), ('salary_min__isnull', True), _connector='OR'), name='job_salary_min_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='jobdescription',
            constraint=models.CheckConstraint(condition=models.Q(('salary_max__gte', 0), ('salary_max__isnull', True), _connector='OR'), name='job_salary_max_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='jobdescription',
            constraint=models.CheckConstraint(condition=models.Q(('min_experience__gte', 0), ('min_experience__isnull', True), _connector='OR'), name='job_min_experience_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='jobdescription',
            constraint=models.CheckConstraint(condition=models.Q(('salary_min__isnull', True), ('salary_max__isnull', True), ('salary_max__gte', models.F('salary_min')), _connector='OR'), name='job_salary_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='jobskill',
            constraint=models.UniqueConstraint(fields=('job', 'skill'), name='uniq_job_skill'),
        ),
    ]
