# Generated by Django 5.2.12 on 2026-03-27 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_candidate_user_links(apps, schema_editor):
    Candidate = apps.get_model("candidates", "Candidate")
    User = apps.get_model("auth", "User")

    for candidate in Candidate.objects.filter(user__isnull=True).exclude(email__isnull=True).exclude(email=""):
        user = User.objects.filter(email__iexact=candidate.email).first()
        if user:
            candidate.user_id = user.id
            candidate.save(update_fields=["user"])


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_resume_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_candidate_user_links, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['is_active', 'updated_at'], name='cand_active_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['created_at'], name='cand_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(('total_experience_years__gte', 0), ('total_experience_years__isnull', True), _connector='OR'), name='candidate_experience_non_negative'),
        ),
    ]
